name: RotationalWrench
main: com.github.joelgodofwar.rw.RotationalWrench
version: 1.14_1.0.2.D14
author: JoelYahwehOfWar
api-version: 1.13

commands:
  RWrench:
    description: Shows RotationalWrench help.
    usage: /<command>

permissions:
  rotationalwrench.showUpdateAvailable:
    description: Shows player that there is a version update.
    default: op
  rotationalwrench.reload:
    description: Allows the player to use "/rwrench reload" command.
    default: op
  rotationalwrench.toggledebug:
    description: Allows the player to use "/rwrench toggledebug" command.
    default: op