package com.github.joelgodofwar.rw.util;

public class Tags_121_2 {
	public static final StringSetTag ANVIL = new StringSetTag(
			"ANVIL", "CHIPPED_ANVIL", "DAMAGED_ANVIL"
			); // 1.11

	public static final StringSetTag BANNER = new StringSetTag(
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER"
			); // 1.11
	public static final StringSetTag WALL_BANNER = new StringSetTag(
			"WHITE_WALL_BANNER",    		"ORANGE_WALL_BANNER",			"MAGENTA_WALL_BANNER",
			"LIGHT_BLUE_WALL_BANNER",		"YELLOW_WALL_BANNER",			"LIME_WALL_BANNER",
			"PINK_WALL_BANNER",			"GRAY_WALL_BANNER",			"LIGHT_GRAY_WALL_BANNER",
			"CYAN_WALL_BANNER",			"PURPLE_WALL_BANNER", 		"BLUE_WALL_BANNER",
			"BROWN_WALL_BANNER",			"GREEN_WALL_BANNER",			"RED_WALL_BANNER",
			"BLACK_WALL_BANNER"
			); // 1.11

	public static final StringSetTag BASALT = new StringSetTag(
			"POLISHED_BASALT"
			); // 1.11

	public static final StringSetTag BEDS = new StringSetTag(
			"WHITE_BED",    		"ORANGE_BED",    		"MAGENTA_BED",
			"LIGHT_BLUE_BED",	"YELLOW_BED",			"LIME_BED",
			"PINK_BED",		"GRAY_BED",	"LIGHT_GRAY_BED",
			"CYAN_BED",	"PURPLE_BED", "BLUE_BED",
			"BROWN_BED",	"GREEN_BED",	"RED_BED",
			"BLACK_BED"
			); // 1.8", 1.12

	public static final StringSetTag BEE = new StringSetTag(
			"BEE_NEST", "BEEHIVE"
			); // 1.11

	public static final StringSetTag BELL = new StringSetTag(
			"BELL"
			); // 1.14

	public static final StringSetTag BONE = new StringSetTag(
			"BONE_BLOCK"
			); // 1.11

	public static final StringSetTag BUTTONS = new StringSetTag(
			"STONE_BUTTON",		"OAK_BUTTON",		"SPRUCE_BUTTON",
			"BIRCH_BUTTON",		"JUNGLE_BUTTON",		"ACACIA_BUTTON",
			"DARK_OAK_BUTTON",	"CRIMSON_BUTTON",	"WARPED_BUTTON",
			"BAMBOO_BUTTON",  "POLISHED_BLACKSTONE_BUTTON",
			"CHERRY_BUTTON"
			); // 1.11

	public static final StringSetTag CAMPFIRES = new StringSetTag(
			"CAMPFIRE", "SOUL_CAMPFIRE"
			); // 1.11

	public static final StringSetTag CARVED_PUMPKIN = new StringSetTag(
			"CARVED_PUMPKIN", "JACK_O_LANTERN"
			); // 1.11

	public static final StringSetTag CHESTS = new StringSetTag(
			"CHEST", "ENDER_CHEST", "TRAPPED_CHEST"
			); // 1.11

	public static final StringSetTag CORAL = new StringSetTag(
			"DEAD_BRAIN_CORAL_FAN",	"DEAD_BUBBLE_CORAL_FAN",	"DEAD_FIRE_CORAL_FAN",
			"DEAD_HORN_CORAL_FAN",	"DEAD_TUBE_CORAL_FAN",

			"BRAIN_CORAL_FAN",	"BUBBLE_CORAL_FAN",	"FIRE_CORAL_FAN",
			"HORN_CORAL_FAN",	"TUBE_CORAL_FAN"
			); // 1.11

	public static final StringSetTag CORAL_WALL = new StringSetTag(
			"DEAD_BRAIN_CORAL_WALL_FAN",	"DEAD_BUBBLE_CORAL_WALL_FAN",	"DEAD_FIRE_CORAL_WALL_FAN",
			"DEAD_HORN_CORAL_WALL_FAN",	"DEAD_TUBE_CORAL_WALL_FAN",

			"BRAIN_CORAL_WALL_FAN",	"BUBBLE_CORAL_WALL_FAN",	"FIRE_CORAL_WALL_FAN",
			"HORN_CORAL_WALL_FAN",	"TUBE_CORAL_WALL_FAN"
			); // 1.11

	public static final StringSetTag CRAFTER = new StringSetTag(
			"CRAFTER"
			);

	public static final StringSetTag DOORS = new StringSetTag(
			"OAK_DOOR", 		"ACACIA_DOOR", 	"BIRCH_DOOR",
			"DARK_OAK_DOOR",	"JUNGLE_DOOR",	"BAMBOO_DOOR",
			"SPRUCE_DOOR",	"IRON_DOOR",		"CHERRY_DOOR",
			"CRIMSON_DOOR",	"WARPED_DOOR",	"COPPER_DOOR",
			"EXPOSED_COPPER_DOOR",	"WEATHERED_COPPER_DOOR",		"OXIDIZED_COPPER_DOOR",
			"WAXED_COPPER_DOOR", 	"WAXED_EXPOSED_COPPER_DOOR",	"WAXED_WEATHERED_COPPER_DOOR",
			"WAXED_OXIDIZED_COPPER_DOOR"
			); // 1.16

	public static final StringSetTag LIGHTNING_ROD = new StringSetTag(
			"LIGHTNING_ROD"
			); // 1.17

	public static final StringSetTag END_ROD = new StringSetTag(
			"END_ROD"
			); // 1.11

	public static final StringSetTag FENCE_GATES = new StringSetTag(
			"OAK_FENCE_GATE", 		"ACACIA_FENCE_GATE", 	"BIRCH_FENCE_GATE",
			"DARK_OAK_FENCE_GATE",	"JUNGLE_FENCE_GATE",		"CHERRY_FENCE_GATE",
			"SPRUCE_FENCE_GATE",		"BAMBOO_FENCE_GATE",
			"CRIMSON_FENCE_GATE",	"WARPED_FENCE_GATE"
			); // 1.16

	public static final StringSetTag GLAZED_TERRACOTTA = new StringSetTag(
			"WHITE_GLAZED_TERRACOTTA",	            "ORANGE_GLAZED_TERRACOTTA",
			"MAGENTA_GLAZED_TERRACOTTA",	            "LIGHT_BLUE_GLAZED_TERRACOTTA",
			"YELLOW_GLAZED_TERRACOTTA",	            "LIME_GLAZED_TERRACOTTA",
			"PINK_GLAZED_TERRACOTTA",	            "GRAY_GLAZED_TERRACOTTA",
			"LIGHT_GRAY_GLAZED_TERRACOTTA",	        "CYAN_GLAZED_TERRACOTTA",
			"PURPLE_GLAZED_TERRACOTTA",	            "BLUE_GLAZED_TERRACOTTA",
			"BROWN_GLAZED_TERRACOTTA",	            "GREEN_GLAZED_TERRACOTTA",
			"RED_GLAZED_TERRACOTTA",		            "BLACK_GLAZED_TERRACOTTA"
			); // 1.12

	public static final StringSetTag HEADS = new StringSetTag(
			"PLAYER_HEAD", "CREEPER_HEAD", "ZOMBIE_HEAD",
			"SKELETON_SKULL", "WITHER_SKELETON_SKULL", "DRAGON_HEAD","PIGLIN_HEAD"
			);

	public static final StringSetTag HEADS2 = new StringSetTag(
			"PLAYER_WALL_HEAD", "CREEPER_WALL_HEAD", "ZOMBIE_WALL_HEAD",
			"SKELETON_WALL_SKULL", "WITHER_SKELETON_WALL_SKULL", "DRAGON_WALL_HEAD",
			"PIGLIN_WALL_HEAD"
			);

	public static final StringSetTag LANTERNS = new StringSetTag(
			"LANTERN", "SOUL_LANTERN"
			); // 1.11

	public static final StringSetTag LOGS = new StringSetTag(
			"OAK_LOG", 				"ACACIA_LOG", 			"BIRCH_LOG",
			"DARK_OAK_LOG",			"JUNGLE_LOG",			"SPRUCE_LOG",
			"STRIPPED_OAK_LOG", 		"STRIPPED_ACACIA_LOG", 	"STRIPPED_BIRCH_LOG",
			"STRIPPED_DARK_OAK_LOG",	"STRIPPED_JUNGLE_LOG",	"CHERRY_LOG",
			"STRIPPED_CHERRY_LOG",	"PALE_OAK_LOG",
			"STRIPPED_SPRUCE_LOG",	"BAMBOO_BLOCK",			"STRIPPED_BAMBOO_BLOCK",
			"CRIMSON_STEM",	 		"WARPED_STEM",			"STRIPPED_CRIMSON_STEM",
			"STRIPPED_WARPED_STEM",	"MANGROVE_LOG",			"STRIPPED_MANGROVE_LOG",
			"STRIPPED_PALE_OAK_LOG"
			); // 1.16

	public static final StringSetTag PILLARS = new StringSetTag(
			"PURPUR_PILLAR", "QUARTZ_PILLAR"
			);

	public static final StringSetTag PISTONS = new StringSetTag(
			"STICKY_PISTON",	"PISTON"
			); // 1.11

	public static final StringSetTag RAILS = new StringSetTag(
			"RAIL",
			"ACTIVATOR_RAIL",
			"POWERED_RAIL",
			"DETECTOR_RAIL"
			); // 1.8

	public static final StringSetTag REDSTONE_COMPONENTS = new StringSetTag(
			"OBSERVER",      "DISPENSER",     		"DROPPER",
			"HOPPER",        "FURNACE",				"CALIBRATED_SCULK_SENSOR",
			"DECORATED_POT",	"CHISELED_BOOKSHELF"
			); // 1.11

	public static final StringSetTag REDSTONE_COMPONENTS2 = new StringSetTag(
			"REPEATER",		"COMPARATOR"
			); // 1.11

	public static final StringSetTag SHULKER = new StringSetTag(
			"SHULKER_BOX",				"WHITE_SHULKER_BOX",			"ORANGE_SHULKER_BOX",
			"MAGENTA_SHULKER_BOX",		"LIGHT_BLUE_SHULKER_BOX",	"YELLOW_SHULKER_BOX",
			"LIME_SHULKER_BOX",			"PINK_SHULKER_BOX",			"GRAY_SHULKER_BOX",
			"LIGHT_GRAY_SHULKER_BOX",	"CYAN_SHULKER_BOX",			"PURPLE_SHULKER_BOX",
			"BLUE_SHULKER_BOX",			"BROWN_SHULKER_BOX",			"GREEN_SHULKER_BOX",
			"RED_SHULKER_BOX",			"BLACK_SHULKER_BOX"
			);

	public static final StringSetTag SIGNS = new StringSetTag(
			"OAK_SIGN",			"SPRUCE_SIGN",		"BIRCH_SIGN",
			"JUNGLE_SIGN",		"ACACIA_SIGN",		"DARK_OAK_SIGN",
			"CRIMSON_SIGN",		"WARPED_SIGN",		"CHERRY_SIGN",
			"BAMBOO_SIGN"
			); // 1.11

	public static final StringSetTag SIGNS2 = new StringSetTag(
			"OAK_WALL_SIGN",			"SPRUCE_WALL_SIGN",		"BIRCH_WALL_SIGN",
			"JUNGLE_WALL_SIGN",		"ACACIA_WALL_SIGN",		"DARK_OAK_WALL_SIGN",
			"CRIMSON_WALL_SIGN",		"WARPED_WALL_SIGN",		"CHERRY_WALL_SIGN",
			"BAMBOO_WALL_SIGN"
			); // 1.11

	public static final StringSetTag SIGNS3 = new StringSetTag(
			"OAK_HANGING_SIGN",			"SPRUCE_HANGING_SIGN",		"BIRCH_HANGING_SIGN",
			"JUNGLE_HANGING_SIGN",		"ACACIA_HANGING_SIGN",		"DARK_OAK_HANGING_SIGN",
			"CRIMSON_HANGING_SIGN",		"WARPED_HANGING_SIGN",		"CHERRY_HANGING_SIGN",
			"BAMBOO_HANGING_SIGN"
			); // 1.11

	public static final StringSetTag SIGNS4 = new StringSetTag(
			"OAK_WALL_HANGING_SIGN",			"SPRUCE_WALL_HANGING_SIGN",		"BIRCH_WALL_HANGING_SIGN",
			"JUNGLE_WALL_HANGING_SIGN",		"ACACIA_WALL_HANGING_SIGN",		"DARK_OAK_WALL_HANGING_SIGN",
			"CRIMSON_WALL_HANGING_SIGN",		"WARPED_WALL_HANGING_SIGN",		"CHERRY_WALL_HANGING_SIGN",
			"BAMBOO_WALL_HANGING_SIGN"
			); // 1.11


	public static final StringSetTag SLABS = new StringSetTag(
			"PURPUR_SLAB",					"OAK_SLAB",							"COBBLESTONE_SLAB",
			"BRICK_SLAB",					"STONE_BRICK_SLAB",					"NETHER_BRICK_SLAB",
			"SPRUCE_SLAB",					"BIRCH_SLAB",						"JUNGLE_SLAB",
			"QUARTZ_SLAB",					"ACACIA_SLAB",						"DARK_OAK_SLAB",
			"PRISMARINE_SLAB",				"PRISMARINE_BRICK_SLAB",				"DARK_PRISMARINE_SLAB",
			"POLISHED_GRANITE_SLAB",			"SMOOTH_RED_SANDSTONE_SLAB",			"MOSSY_STONE_BRICK_SLAB",
			"POLISHED_DIORITE_SLAB",			"MOSSY_COBBLESTONE_SLAB",			"END_STONE_BRICK_SLAB",
			"STONE_SLAB",					"SMOOTH_SANDSTONE_SLAB",				"SMOOTH_QUARTZ_SLAB",
			"GRANITE_SLAB",					"ANDESITE_SLAB",						"RED_NETHER_BRICK_SLAB",
			"POLISHED_ANDESITE_SLAB",		"DIORITE_SLAB",						"CHERRY_SLAB",
			"SANDSTONE_SLAB",				"RED_SANDSTONE_SLAB",				"BAMBOO_SLAB",
			"BLACKSTONE_SLAB",				"POLISHED_BLACKSTONE_SLAB",			"POLISHED_BLACKSTONE_BRICK_SLAB",
			"CRIMSON_SLAB",					"WARPED_SLAB",						"BAMBOO_MOSAIC_SLAB",
			"DEEPSLATE_BRICK_SLAB",			"DEEPSLATE_TILE_SLAB",				"COBBLED_DEEPSLATE_SLAB",
			"POLISHED_DEEPSLATE_SLAB",		"CUT_COPPER_SLAB",					"EXPOSED_CUT_COPPER_SLAB",
			"WEATHERED_CUT_COPPER_SLAB",		"OXIDIZED_CUT_COPPER_SLAB",			"WAXED_CUT_COPPER_SLAB",
			"WAXED_EXPOSED_CUT_COPPER_SLAB",	"WAXED_WEATHERED_CUT_COPPER_SLAB",	"WAXED_OXIDIZED_CUT_COPPER_SLAB"
			); // 1.16

	public static final StringSetTag STAIRS = new StringSetTag(
			"PURPUR_STAIRS",						"OAK_STAIRS",						"COBBLESTONE_STAIRS",
			"BRICK_STAIRS",						"STONE_BRICK_STAIRS",				"NETHER_BRICK_STAIRS",
			"SANDSTONE_STAIRS",					"SPRUCE_STAIRS",						"BIRCH_STAIRS",
			"JUNGLE_STAIRS",						"QUARTZ_STAIRS",						"ACACIA_STAIRS",
			"DARK_OAK_STAIRS",					"PRISMARINE_STAIRS",					"PRISMARINE_BRICK_STAIRS",
			"DARK_PRISMARINE_STAIRS",			"RED_SANDSTONE_STAIRS",				"POLISHED_GRANITE_STAIRS",
			"SMOOTH_RED_SANDSTONE_STAIRS",		"MOSSY_STONE_BRICK_STAIRS",			"POLISHED_DIORITE_STAIRS",
			"MOSSY_COBBLESTONE_STAIRS",			"END_STONE_BRICK_STAIRS",			"STONE_STAIRS",
			"SMOOTH_SANDSTONE_STAIRS",			"SMOOTH_QUARTZ_STAIRS",				"GRANITE_STAIRS",
			"ANDESITE_STAIRS",					"RED_NETHER_BRICK_STAIRS",			"POLISHED_ANDESITE_STAIRS",
			"DIORITE_STAIRS",					"BAMBOO_STAIRS",						"BAMBOO_MOSAIC_STAIRS",
			"BLACKSTONE_STAIRS",					"POLISHED_BLACKSTONE_STAIRS",		"POLISHED_BLACKSTONE_BRICK_STAIRS",
			"CRIMSON_STAIRS",					"WARPED_STAIRS",						"CHERRY_STAIRS",
			"DEEPSLATE_BRICK_STAIRS",			"DEEPSLATE_TILE_STAIRS",				"COBBLED_DEEPSLATE_STAIRS",
			"POLISHED_DEEPSLATE_STAIRS",			"CUT_COPPER_STAIRS",					"EXPOSED_CUT_COPPER_STAIRS",
			"WEATHERED_CUT_COPPER_STAIRS",		"OXIDIZED_CUT_COPPER_STAIRS",		"WAXED_CUT_COPPER_STAIRS",
			"WAXED_EXPOSED_CUT_COPPER_STAIRS",	"WAXED_WEATHERED_CUT_COPPER_STAIRS",	"WAXED_OXIDIZED_CUT_COPPER_STAIRS"
			); // 1.16

	public static final StringSetTag TORCH = new StringSetTag(
			"WALL_TORCH	",	"REDSTONE_WALL_TORCH",
			"TORCH	",		"REDSTONE_TORCH"
			); // 1.11

	public static final StringSetTag TORCH2 = new StringSetTag(
			"SOUL_WALL_TORCH",	 "SOUL_TORCH"
			); // 1.11

	public static final StringSetTag TRAPDOORS = new StringSetTag(
			"IRON_TRAPDOOR",		"OAK_TRAPDOOR", 		"SPRUCE_TRAPDOOR",
			"BIRCH_TRAPDOOR",	"JUNGLE_TRAPDOOR",	"ACACIA_TRAPDOOR",
			"DARK_OAK_TRAPDOOR",	"CHERRY_TRAPDOOR",	"BAMBOO_TRAPDOOR",
			"CRIMSON_TRAPDOOR",	"WARPED_TRAPDOOR",	"COPPER_TRAPDOOR",
			"EXPOSED_COPPER_TRAPDOOR",		"WEATHERED_COPPER_TRAPDOOR",		"OXIDIZED_COPPER_TRAPDOOR",
			"WAXED_COPPER_TRAPDOOR",			"WAXED_EXPOSED_COPPER_TRAPDOOR",	"WAXED_WEATHERED_COPPER_TRAPDOOR",
			"WAXED_OXIDIZED_COPPER_TRAPDOOR"
			); // 1.16

	public static final StringSetTag WALL = new StringSetTag(
			"ANDESITE_WALL",	"BLACKSTONE_WALL",	"BRICK_WALL",
			"COBBLED_DEEPSLATE_WALL",	"COBBLESTONE_WALL",	"DEEPSLATE_BRICK_WALL",
			"DEEPSLATE_TILE_WALL",	"DIORITE_WALL",	"END_STONE_BRICK_WALL",
			"MOSSY_COBBLESTONE_WALL",	"MOSSY_STONE_BRICK_WALL",	"POLISHED_BLACKSTONE_WALL",
			"POLISHED_BLACKSTONE_BRICK_WALL",	"PRISMARINE_WALL",	"SANDSTONE_WALL",
			"RED_SANDSTONE_WALL",	"STONE_BRICK_WALL",	"TUFF_WALL",	"TUFF_BRICK_WALL",
			"POLISHED_TUFF_WALL"
			);

	public static final StringSetTag WORKSTATIONS = new StringSetTag(
			"BLAST_FURNACE", 	"SMOKER",
			"BARREL",		 	"LECTERN",
			"LOOM",				"STONECUTTER",		"GRINDSTONE"
			); // 1.14", 1.16

	public static final StringSetTag NO_BUTTONS = new StringSetTag(
			"ARMOR_STAND",
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER",
			"BELL",					"BREWING_STAND",			"CACTUS",
			"WHITE_CARPET",    		"ORANGE_CARPET",			"MAGENTA_CARPET",
			"LIGHT_BLUE_CARPET",		"YELLOW_CARPET",			"LIME_CARPET",
			"PINK_CARPET",			"GRAY_CARPET",			"LIGHT_GRAY_CARPET",
			"CYAN_CARPET",			"PURPLE_CARPET", 		"BLUE_CARPET",
			"BROWN_CARPET",			"GREEN_CARPET",			"RED_CARPET",
			"BLACK_CARPET",			"CAULDRON",
			"CHORUS_PLANT",			"COBWEB",				"END_ROD",
			"CHEST", 				"ENDER_CHEST",				"TRAPPED_CHEST",
			"HOPPER", 				"ANVIL",						"CHIPPED_ANVIL",
			"DAMAGED_ANVIL",			"GRINDSTONE", 				"STONECUTTER",
			"ENCHANTING_TABLE",		"END_PORTAL_FRAME",			"HONEY_BLOCK",
			"COBBLESTONE_WALL",	    "BRICK_WALL",				"STONE_BRICK_WALL",
			"NETHER_BRICK_WALL",	    "SANDSTONE_WALL",			"PRISMARINE_WALL",
			"RED_SANDSTONE_WALL",	"MOSSY_STONE_BRICK_WALL",	"MOSSY_COBBLESTONE_WALL",
			"END_STONE_BRICK_WALL",	"GRANITE_WALL",
			"ANDESITE_WALL",			"RED_NETHER_BRICK_WALL",		"DIORITE_WALL",
			"BLACKSTONE_WALL",		"POLISHED_BLACKSTONE_WALL",	"POLISHED_BLACKSTONE_BRICK_WALL",
			"OAK_FENCE",				"NETHER_BRICK_FENCE",		"SPRUCE_FENCE",
			"BIRCH_FENCE",			"JUNGLE_FENCE",				"ACACIA_FENCE",
			"DARK_OAK_FENCE",		"CRIMSON_FENCE",				"WARPED_FENCE",
			"LANTERN",				"SOUL_LANTERN",				"CAMPFIRE",
			"SOUL_CAMPFIRE",			"CHAIN",						"CHERRY_LEAVES",
			"OAK_LEAVES", 			"ACACIA_LEAVES", 			"BIRCH_LEAVES",
			"DARK_OAK_LEAVES",		"JUNGLE_LEAVES",				"SPRUCE_LEAVES",
			"LECTERN",
			"WHITE_BED",    			"ORANGE_BED",				"MAGENTA_BED",
			"LIGHT_BLUE_BED",		"YELLOW_BED",				"LIME_BED",
			"PINK_BED",				"GRAY_BED",					"LIGHT_GRAY_BED",
			"CYAN_BED",				"PURPLE_BED", 				"BLUE_BED",
			"BROWN_BED",				"GREEN_BED",					"RED_BED",
			"BLACK_BED",				"IRON_BARS",
			"OAK_FENCE_GATE", 		"ACACIA_FENCE_GATE", 		"BIRCH_FENCE_GATE",
			"DARK_OAK_FENCE_GATE",	"JUNGLE_FENCE_GATE",
			"SPRUCE_FENCE_GATE",
			"CRIMSON_FENCE_GATE",	"WARPED_FENCE_GATE",
			"DAYLIGHT_DETECTOR",		"FLOWER_POT",
			"WHITE_STAINED_GLASS_PANE",    		"ORANGE_STAINED_GLASS_PANE",			"MAGENTA_STAINED_GLASS_PANE",
			"LIGHT_BLUE_STAINED_GLASS_PANE",		"YELLOW_STAINED_GLASS_PANE",			"LIME_STAINED_GLASS_PANE",
			"PINK_STAINED_GLASS_PANE",			"GRAY_STAINED_GLASS_PANE",			"LIGHT_GRAY_STAINED_GLASS_PANE",
			"CYAN_STAINED_GLASS_PANE",			"PURPLE_STAINED_GLASS_PANE", 		"BLUE_STAINED_GLASS_PANE",
			"BROWN_STAINED_GLASS_PANE",			"GREEN_STAINED_GLASS_PANE",			"RED_STAINED_GLASS_PANE",
			"BLACK_STAINED_GLASS_PANE",
			"PLAYER_HEAD",			"CREEPER_HEAD",			"ZOMBIE_HEAD",
			"SKELETON_SKULL",		"WITHER_SKELETON_SKULL", "DRAGON_HEAD",
			"LILY_PAD",				"SCAFFOLDING",
			"BAMBOO",				"BAMBOO_SAPLING",
			"WHITE_WALL_BANNER",    		"ORANGE_WALL_BANNER",			"MAGENTA_WALL_BANNER",
			"LIGHT_BLUE_WALL_BANNER",		"YELLOW_WALL_BANNER",			"LIME_WALL_BANNER",
			"PINK_WALL_BANNER",			"GRAY_WALL_BANNER",			"LIGHT_GRAY_WALL_BANNER",
			"CYAN_WALL_BANNER",			"PURPLE_WALL_BANNER", 		"BLUE_WALL_BANNER",
			"BROWN_WALL_BANNER",			"GREEN_WALL_BANNER",			"RED_WALL_BANNER",
			"BLACK_WALL_BANNER",
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER"

			); // 1.16

	public static final StringSetTag NO_LANTERNS = new StringSetTag(
			"CHEST", "ENDER_CHEST", "TRAPPED_CHEST",
			"HOPPER", "ANVIL", "CHIPPED_ANVIL", "DAMAGED_ANVIL",
			"GRINDSTONE", "STONECUTTER", "ENCHANTING_TABLE",
			"END_PORTAL_FRAME",	"HONEY_BLOCK"
			);

	public static final StringSetTag NO_TORCH_SIDE = new StringSetTag(
			"ANVIL",					"CHIPPED_ANVIL",    		"DAMAGED_ANVIL",
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER",
			"WHITE_BED",    			"ORANGE_BED",			"MAGENTA_BED",
			"LIGHT_BLUE_BED",		"YELLOW_BED",			"LIME_BED",
			"PINK_BED",				"GRAY_BED",				"LIGHT_GRAY_BED",
			"CYAN_BED",				"PURPLE_BED", 			"BLUE_BED",
			"BROWN_BED",				"GREEN_BED",				"RED_BED",
			"BLACK_BED",
			"BELL",					"BREWING_STAND",			"CACTUS",
			"CAMPFIRE",				"SOUL_CAMPFIRE",			"CAULDRON",
			"WHITE_CARPET",    		"ORANGE_CARPET",			"MAGENTA_CARPET",
			"LIGHT_BLUE_CARPET",		"YELLOW_CARPET",			"LIME_CARPET",
			"PINK_CARPET",			"GRAY_CARPET",			"LIGHT_GRAY_CARPET",
			"CYAN_CARPET",			"PURPLE_CARPET", 		"BLUE_CARPET",
			"BROWN_CARPET",			"GREEN_CARPET",			"RED_CARPET",
			"BLACK_CARPET",
			"CHEST", 				"CHORUS_PLANT",			"COBWEB",
			"DAYLIGHT_DETECTOR",		"ENCHANTING_TABLE",		"END_ROD",
			"ENDER_CHEST",			"END_PORTAL_FRAME",		"FLOWER_POT",
			"OAK_FENCE", 			"ACACIA_FENCE",		 	"BIRCH_FENCE",
			"DARK_OAK_FENCE",		"JUNGLE_FENCE",			"SPRUCE_FENCE",
			"CRIMSON_FENCE",			"WARPED_FENCE",
			"OAK_FENCE_GATE", 		"ACACIA_FENCE_GATE", 	"BIRCH_FENCE_GATE",
			"DARK_OAK_FENCE_GATE",	"JUNGLE_FENCE_GATE",
			"SPRUCE_FENCE_GATE",
			"CRIMSON_FENCE_GATE",	"WARPED_FENCE_GATE",
			"DIRT_PATH",				"GRINDSTONE",			"IRON_BARS",
			"LANTERN",				"SOUL_LANTERN",
			"OAK_LEAVES", 			"ACACIA_LEAVES", 		"BIRCH_LEAVES",
			"DARK_OAK_LEAVES",		"JUNGLE_LEAVES",			"SPRUCE_LEAVES",
			"LECTERN",				"LILY_PAD",				"HONEY_BLOCK",
			"HOPPER",				"SCAFFOLDING",			"STONECUTTER",
			"TRAPPED_CHEST",			"IRON_BARS",				"CHAIN",
			"GLASS_PANE",
			"PLAYER_HEAD",			"CREEPER_HEAD",			"ZOMBIE_HEAD",
			"SKELETON_SKULL",		"WITHER_SKELETON_SKULL", "DRAGON_HEAD",
			"WHITE_STAINED_GLASS_PANE",    		"ORANGE_STAINED_GLASS_PANE",			"MAGENTA_STAINED_GLASS_PANE",
			"LIGHT_BLUE_STAINED_GLASS_PANE",		"YELLOW_STAINED_GLASS_PANE",			"LIME_STAINED_GLASS_PANE",
			"PINK_STAINED_GLASS_PANE",			"GRAY_STAINED_GLASS_PANE",			"LIGHT_GRAY_STAINED_GLASS_PANE",
			"CYAN_STAINED_GLASS_PANE",			"PURPLE_STAINED_GLASS_PANE", 		"BLUE_STAINED_GLASS_PANE",
			"BROWN_STAINED_GLASS_PANE",			"GREEN_STAINED_GLASS_PANE",			"RED_STAINED_GLASS_PANE",
			"BLACK_STAINED_GLASS_PANE",			"CHERRY_LEAVES",
			"BAMBOO",				"BAMBOO_SAPLING",		"FARMLAND"

			); // 1.16

	public static final StringSetTag NO_TORCH_TOP = new StringSetTag(
			"ARMOR_STAND",
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER",
			"WHITE_BED",    			"ORANGE_BED",			"MAGENTA_BED",
			"LIGHT_BLUE_BED",		"YELLOW_BED",			"LIME_BED",
			"PINK_BED",				"GRAY_BED",				"LIGHT_GRAY_BED",
			"CYAN_BED",				"PURPLE_BED", 			"BLUE_BED",
			"BROWN_BED",				"GREEN_BED",				"RED_BED",
			"BLACK_BED",
			"BREWING_STAND",			"CACTUS",
			"CAMPFIRE",				"SOUL_CAMPFIRE",			"CAULDRON",
			"WHITE_CARPET",    		"ORANGE_CARPET",			"MAGENTA_CARPET",
			"LIGHT_BLUE_CARPET",		"YELLOW_CARPET",			"LIME_CARPET",
			"PINK_CARPET",			"GRAY_CARPET",			"LIGHT_GRAY_CARPET",
			"CYAN_CARPET",			"PURPLE_CARPET", 		"BLUE_CARPET",
			"BROWN_CARPET",			"GREEN_CARPET",			"RED_CARPET",
			"BLACK_CARPET",
			"CHEST", 				"CHORUS_PLANT",			"COBWEB",
			"COMPOSTER",				"DAYLIGHT_DETECTOR",		"ENCHANTING_TABLE",
			"ENDER_CHEST",			"END_PORTAL_FRAME",		"FLOWER_POT",
			"OAK_FENCE_GATE", 		"ACACIA_FENCE_GATE", 	"BIRCH_FENCE_GATE",
			"DARK_OAK_FENCE_GATE",	"JUNGLE_FENCE_GATE",
			"SPRUCE_FENCE_GATE",
			"CRIMSON_FENCE_GATE",	"WARPED_FENCE_GATE",
			"DIRT_PATH",
			"LANTERN",				"SOUL_LANTERN",
			"OAK_LEAVES", 			"ACACIA_LEAVES", 		"BIRCH_LEAVES",
			"DARK_OAK_LEAVES",		"JUNGLE_LEAVES",			"SPRUCE_LEAVES",
			"LECTERN",				"LILY_PAD",				"HONEY_BLOCK",
			"HOPPER",				"STONECUTTER",			"TRAPPED_CHEST",
			"PLAYER_HEAD",			"CREEPER_HEAD",			"ZOMBIE_HEAD",
			"SKELETON_SKULL",		"WITHER_SKELETON_SKULL", "DRAGON_HEAD",
			"BAMBOO",				"BAMBOO_SAPLING",		"CHERRY_LEAVES"

			); // 1.16

	public static final StringSetTag YES_SIGNS = new StringSetTag(
			"ANVIL", 			"CHIPPED_ANVIL", 	"DAMAGED_ANVIL",
			"ENCHANTING_TABLE",	"GRINDSTONE",
			"LANTERN", 			"SOUL_LANTERN"
			);

	public static final StringSetTag NO_SIGNS_SIDE = new StringSetTag(
			"ARMOR_STAND",			"CACTUS",
			"WHITE_CARPET",    		"ORANGE_CARPET",			"MAGENTA_CARPET",
			"LIGHT_BLUE_CARPET",		"YELLOW_CARPET",			"LIME_CARPET",
			"PINK_CARPET",			"GRAY_CARPET",			"LIGHT_GRAY_CARPET",
			"CYAN_CARPET",			"PURPLE_CARPET", 		"BLUE_CARPET",
			"BROWN_CARPET",			"GREEN_CARPET",			"RED_CARPET",
			"BLACK_CARPET",			"CHORUS_FLOWER",			"CHORUS_PLANT",
			"FLOWER_POT",			"LILY_PAD",				"SCAFFOLDING",
			"PLAYER_HEAD",			"CREEPER_HEAD",			"ZOMBIE_HEAD",
			"SKELETON_SKULL",		"WITHER_SKELETON_SKULL", "DRAGON_HEAD",
			"STONE_BUTTON",			"OAK_BUTTON",			"SPRUCE_BUTTON",
			"BIRCH_BUTTON",			"JUNGLE_BUTTON",			"ACACIA_BUTTON",
			"DARK_OAK_BUTTON",		"CRIMSON_BUTTON",		"WARPED_BUTTON",
			"POLISHED_BLACKSTONE_BUTTON",
			"LEVER",					"END_ROD",
			"TORCH",					"SOUL_TORCH",			"REDSTONE_TORCH",
			"WALL_TORCH",			"SOUL_WALL_TORCH",		"REDSTONE_WALL_TORCH"
			);

	public static final StringSetTag NO_SIGNS_TOP = new StringSetTag(
			"ARMOR_STAND",
			"WHITE_BANNER",    		"ORANGE_BANNER",			"MAGENTA_BANNER",
			"LIGHT_BLUE_BANNER",		"YELLOW_BANNER",			"LIME_BANNER",
			"PINK_BANNER",			"GRAY_BANNER",			"LIGHT_GRAY_BANNER",
			"CYAN_BANNER",			"PURPLE_BANNER", 		"BLUE_BANNER",
			"BROWN_BANNER",			"GREEN_BANNER",			"RED_BANNER",
			"BLACK_BANNER",
			"CACTUS",
			"WHITE_CARPET",    		"ORANGE_CARPET",			"MAGENTA_CARPET",
			"LIGHT_BLUE_CARPET",		"YELLOW_CARPET",			"LIME_CARPET",
			"PINK_CARPET",			"GRAY_CARPET",			"LIGHT_GRAY_CARPET",
			"CYAN_CARPET",			"PURPLE_CARPET", 		"BLUE_CARPET",
			"BROWN_CARPET",			"GREEN_CARPET",			"RED_CARPET",
			"BLACK_CARPET",			"CHORUS_FLOWER",			"CHORUS_PLANT",
			"FLOWER_POT",			"LILY_PAD",				"SCAFFOLDING",
			"PLAYER_HEAD",			"CREEPER_HEAD",			"ZOMBIE_HEAD",
			"SKELETON_SKULL",		"WITHER_SKELETON_SKULL", "DRAGON_HEAD",
			"STONE_BUTTON",			"OAK_BUTTON",			"SPRUCE_BUTTON",
			"BIRCH_BUTTON",			"JUNGLE_BUTTON",			"ACACIA_BUTTON",
			"DARK_OAK_BUTTON",		"CRIMSON_BUTTON",		"WARPED_BUTTON",
			"POLISHED_BLACKSTONE_BUTTON",
			"LEVER",					"DIRT_PATH",
			"TORCH",					"SOUL_TORCH",			"REDSTONE_TORCH",
			"WALL_TORCH",			"SOUL_WALL_TORCH",		"REDSTONE_WALL_TORCH"
			);

}